# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 05:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_from', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('available_for_x_minutes', models.IntegerField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_exam', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('questions_amount', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('current_index', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSessionQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='Open', max_length=100)),
                ('question', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('answer', models.CharField(max_length=100, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.AssignmentSession')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_amount', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField(default=5)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('stream_description', models.TextField(default='', verbose_name='Stream description')),
                ('stream_code', models.CharField(max_length=50, unique=True)),
                ('enroll_key', models.CharField(max_length=20)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('function_code', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Subject'),
        ),
        migrations.AddField(
            model_name='stream',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmenttopic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Subject'),
        ),
        migrations.AddField(
            model_name='assignmenttopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Topic'),
        ),
        migrations.AddField(
            model_name='assignmentsessionquestions',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Topic'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Stream'),
        ),
    ]
