# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsession',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentsessionquestions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
