# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20190107_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='subject',
        ),
    ]
