# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-07 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20190107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentsession',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
    ]
