# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-06 08:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20190205_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttopic',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, to='process.Topic'),
        ),
    ]
