# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-09 03:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20190206_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsessionquestions',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', null=True, verbose_name='Question description'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Question description'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Stream description'),
        ),
    ]
