# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_auto_20190213_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_code',
        ),
    ]
