# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-26 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_auto_20190218_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttopic',
            name='topic',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, to='process.Topic'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rn_stream', to=settings.AUTH_USER_MODEL),
        ),
    ]
