# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20190226_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='is_exam',
            new_name='active',
        ),
    ]
