# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0020_auto_20190522_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttopic',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_topic_for', to='process.Assignment'),
        ),
    ]
